# Generated by Django 2.0.3 on 2018-04-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('number', models.IntegerField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('town_city', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('occupation', models.CharField(max_length=250)),
            ],
        ),
    ]
