# Generated by Django 2.0.3 on 2018-04-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stori', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='number',
            field=models.IntegerField(),
        ),
    ]
