# Generated by Django 2.0.3 on 2018-05-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stori', '0007_member_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date_birth',
            field=models.DateField(null=True),
        ),
    ]
