# Generated by Django 2.0.3 on 2018-06-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stori', '0009_auto_20180606_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='pics',
            field=models.ImageField(default='pic_folder/all', upload_to='pic_folder/'),
        ),
    ]
