# Generated by Django 2.0.3 on 2018-06-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stori', '0010_member_pics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='pics',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
