# Generated by Django 2.0.3 on 2018-06-22 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stori', '0011_auto_20180615_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=250, null=True)),
                ('month', models.CharField(blank=True, max_length=250, null=True)),
                ('offering_gotten', models.CharField(blank=True, max_length=250, null=True)),
                ('offering_welfare', models.CharField(blank=True, max_length=250, null=True)),
                ('outstanding_offering', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week1', models.CharField(blank=True, max_length=250, null=True)),
                ('week2', models.CharField(blank=True, max_length=250, null=True)),
                ('week3', models.CharField(blank=True, max_length=250, null=True)),
                ('week4', models.CharField(blank=True, max_length=250, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stori.Account')),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, default='0244231035', max_length=250),
        ),
    ]
